"""SQLite helpers shared by the server components."""

from __future__ import annotations

import logging
import os
import socket
import sqlite3
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence

from server import init_db as cli_init_db

from .logging_utils import get_logger


DEFAULT_SERVER_DB_PATH = Path(cli_init_db.DEFAULT_DB_PATH)
ENV_DB_PATH = os.environ.get("RAI_SERVER_DB_PATH")
DB_PATH = Path(ENV_DB_PATH) if ENV_DB_PATH else DEFAULT_SERVER_DB_PATH

_LOGGER = get_logger(__name__)


def ensure_schema(path: Path | None = None) -> None:
    """Ensure the database schema exists by applying pending migrations."""

    target = Path(path) if path else DB_PATH
    cli_init_db.apply_migrations(db_path=target, logger=_LOGGER)


def load_apps(path: Path | None = None) -> List[Dict[str, object]]:
    """Return the active installs used by the interpreter catalogue."""

    target = Path(path) if path else DB_PATH
    ensure_schema(target)
    with sqlite3.connect(target) as conn:
        conn.row_factory = sqlite3.Row
        cursor = conn.execute(
            """
            SELECT
                lower(ac.display_name) AS normalized_name,
                ac.display_name,
                CASE
                    WHEN inst.package_id IS NOT NULL THEN 'uwp'
                    ELSE inst.source
                END AS app_type,
                bin.exe_path,
                inst.source,
                pkg.package_fullname AS app_id,
                inst.last_seen_at,
                host.hostname
            FROM installs AS inst
            JOIN hosts AS host ON host.id = inst.host_id
            JOIN apps_catalog AS ac ON ac.id = inst.app_catalog_id
            LEFT JOIN packages AS pkg ON pkg.id = inst.package_id
            LEFT JOIN binaries AS bin ON bin.id = inst.binary_id
            WHERE inst.is_active = 1 AND inst.removed_at IS NULL
            ORDER BY inst.last_seen_at DESC
            """
        )
        apps: List[Dict[str, object]] = []
        for row in cursor.fetchall():
            apps.append(
                {
                    "name": row["normalized_name"],
                    "display_name": row["display_name"],
                    "type": row["app_type"],
                    "exe_path": row["exe_path"],
                    "app_id": row["app_id"],
                    "source": row["source"],
                    "last_seen": row["last_seen_at"],
                    "hostname": row["hostname"],
                }
            )
        return apps


def ingest_scan(
    hostname: str,
    apps: Sequence[Mapping[str, object]],
    *,
    db_path: Path | None = None,
    trace_id: str | None = None,
    logger: logging.Logger | None = None,
) -> int:
    """Persist a scan payload generated by the client scanner."""

    if not isinstance(hostname, str) or not hostname.strip():
        raise ValueError("hostname must be a non-empty string")

    target = Path(db_path) if db_path else DB_PATH
    ensure_schema(target)

    log = logger or _LOGGER
    normalised_host = hostname.strip()

    processed = 0
    with _connect(target) as conn:
        host_id = _upsert_host(conn, normalised_host)
        scan_id = _start_scan(conn, host_id)
        dedupe: set[str] = set()

        for item in apps:
            if not isinstance(item, Mapping):
                continue
            record = _prepare_record(item)
            if record is None:
                continue

            identity = record.pop("identity", None)
            if identity:
                if identity in dedupe:
                    continue
                dedupe.add(identity)

            if _insert_scan_item(conn, host_id, scan_id, record):
                processed += 1

        _finalise_scan(conn, scan_id, processed)

    log.info(
        "ingest_scan completed",
        extra={"host": normalised_host, "items": processed, "trace_id": trace_id},
    )
    return processed


def scan_and_update_db(path: Path | None = None) -> int:
    """Execute a local scan using the client module and persist the results."""

    target = Path(path) if path else DB_PATH
    ensure_schema(target)

    from ..client import scanner  # Lazy import avoids Windows-only deps at import time

    try:
        apps = scanner.scan_apps(full=True)
    except Exception as exc:  # pragma: no cover - scanner is Windows-specific
        _LOGGER.warning("scan_apps failed", extra={"error": str(exc)})
        raise

    hostname = socket.gethostname()
    return ingest_scan(hostname, apps, db_path=target, logger=_LOGGER)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _connect(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    conn.execute("PRAGMA journal_mode=WAL;")
    conn.execute("PRAGMA synchronous=NORMAL;")
    return conn


def _upsert_host(conn: sqlite3.Connection, hostname: str) -> int:
    cursor = conn.execute(
        "INSERT OR IGNORE INTO hosts (hostname) VALUES (?)",
        (hostname,),
    )
    if cursor.lastrowid:
        return int(cursor.lastrowid)
    conn.execute(
        "UPDATE hosts SET updated_at = CURRENT_TIMESTAMP WHERE hostname = ?",
        (hostname,),
    )
    row = conn.execute(
        "SELECT id FROM hosts WHERE hostname = ?",
        (hostname,),
    ).fetchone()
    if not row:
        raise RuntimeError("failed to resolve host id")
    return int(row[0])


def _start_scan(conn: sqlite3.Connection, host_id: int) -> int:
    cursor = conn.execute(
        "INSERT INTO scans (host_id, started_at) VALUES (?, CURRENT_TIMESTAMP)",
        (host_id,),
    )
    return int(cursor.lastrowid)


def _finalise_scan(conn: sqlite3.Connection, scan_id: int, total_items: int) -> None:
    conn.execute(
        "UPDATE scans SET completed_at = CURRENT_TIMESTAMP, total_items = ? WHERE id = ?",
        (total_items, scan_id),
    )


def _prepare_record(item: Mapping[str, object]) -> Optional[Dict[str, object]]:
    raw_name = str(item.get("name") or item.get("display_name") or "").strip()
    if not raw_name:
        return None

    normalized_name = _normalize_name(raw_name)
    if not normalized_name:
        return None

    publisher = str(item.get("publisher") or "").strip()
    version = str(item.get("version") or "").strip()
    source = _normalise_source(item.get("source"))
    exe_path = _clean_str(item.get("exe_path"))
    target_path = _clean_str(item.get("target_path"))
    uwp_fullname = _clean_str(
        item.get("uwp_package_fullname")
        or item.get("uwp_package")
        or item.get("aumid")
    )
    icon_path = _clean_str(item.get("icon_path"))
    file_hash = _clean_str(item.get("hash") or item.get("file_hash"))
    security_flag = 1 if bool(item.get("security_flag")) else 0
    security_reason = _clean_str(item.get("security_reason"))
    scanned_at = _clean_str(item.get("scanned_at"))
    if not scanned_at:
        scanned_at = datetime.utcnow().isoformat(timespec="seconds")

    identity = (uwp_fullname or exe_path or normalized_name).lower()

    return {
        "raw_name": raw_name,
        "normalized_name": normalized_name,
        "publisher": publisher,
        "version": version,
        "source": source,
        "exe_path": exe_path,
        "target_path": target_path,
        "uwp_package_fullname": uwp_fullname,
        "icon_path": icon_path,
        "file_hash": file_hash,
        "security_flag": security_flag,
        "security_reason": security_reason,
        "scanned_at": scanned_at,
        "identity": identity,
    }


def _insert_scan_item(
    conn: sqlite3.Connection,
    host_id: int,
    scan_id: int,
    record: Dict[str, object],
) -> bool:
    app_catalog_id = _upsert_app_catalog(
        conn,
        record["raw_name"],
        record["normalized_name"],
        record["publisher"],
    )
    package_id = _upsert_package(
        conn,
        record.get("uwp_package_fullname"),
        record["raw_name"],
        record["publisher"],
        record.get("version"),
    )
    binary_id = _upsert_binary(
        conn,
        record.get("exe_path"),
        record.get("target_path"),
        record.get("icon_path"),
        record.get("file_hash"),
        record.get("version"),
        record.get("publisher"),
    )

    cursor = conn.execute(
        """
        INSERT OR IGNORE INTO scan_items (
            scan_id,
            host_id,
            app_catalog_id,
            package_id,
            binary_id,
            source,
            raw_name,
            raw_version,
            raw_publisher,
            exe_path,
            uwp_package_fullname,
            icon_path,
            file_hash,
            security_flag,
            security_reason,
            scanned_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            scan_id,
            host_id,
            app_catalog_id,
            package_id,
            binary_id,
            record["source"],
            record["raw_name"],
            record.get("version"),
            record["publisher"],
            record.get("exe_path"),
            record.get("uwp_package_fullname"),
            record.get("icon_path"),
            record.get("file_hash"),
            record["security_flag"],
            record.get("security_reason"),
            record["scanned_at"],
        ),
    )
    return cursor.rowcount != 0


def _upsert_app_catalog(
    conn: sqlite3.Connection,
    display_name: str,
    normalized_name: str,
    publisher: str,
) -> int:
    cursor = conn.execute(
        """
        INSERT INTO apps_catalog (display_name, normalized_name, publisher)
        VALUES (?, ?, ?)
        ON CONFLICT(normalized_name, publisher) DO UPDATE SET
            display_name = excluded.display_name,
            updated_at = CURRENT_TIMESTAMP
        """,
        (display_name, normalized_name, publisher),
    )
    if cursor.lastrowid:
        return int(cursor.lastrowid)
    row = conn.execute(
        "SELECT id FROM apps_catalog WHERE normalized_name = ? AND publisher = ?",
        (normalized_name, publisher),
    ).fetchone()
    if not row:
        raise RuntimeError("failed to resolve app catalog id")
    return int(row[0])


def _upsert_package(
    conn: sqlite3.Connection,
    package_fullname: Optional[str],
    package_name: str,
    publisher: str,
    version: Optional[str],
) -> Optional[int]:
    if not package_fullname:
        return None
    cursor = conn.execute(
        """
        INSERT INTO packages (package_fullname, package_name, publisher, version)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(package_fullname) DO UPDATE SET
            package_name = excluded.package_name,
            publisher = COALESCE(NULLIF(excluded.publisher, ''), publisher),
            version = COALESCE(NULLIF(excluded.version, ''), version),
            updated_at = CURRENT_TIMESTAMP
        """,
        (package_fullname, package_name, publisher, version or None),
    )
    if cursor.lastrowid:
        return int(cursor.lastrowid)
    row = conn.execute(
        "SELECT id FROM packages WHERE package_fullname = ?",
        (package_fullname,),
    ).fetchone()
    return int(row[0]) if row else None


def _upsert_binary(
    conn: sqlite3.Connection,
    exe_path: Optional[str],
    target_path: Optional[str],
    icon_path: Optional[str],
    file_hash: Optional[str],
    version: Optional[str],
    publisher: Optional[str],
) -> Optional[int]:
    if not exe_path:
        return None
    cursor = conn.execute(
        """
        INSERT INTO binaries (exe_path, target_path, icon_path, file_hash, version, publisher)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(exe_path) DO UPDATE SET
            target_path = COALESCE(NULLIF(excluded.target_path, ''), target_path),
            icon_path = COALESCE(NULLIF(excluded.icon_path, ''), icon_path),
            file_hash = COALESCE(NULLIF(excluded.file_hash, ''), file_hash),
            version = COALESCE(NULLIF(excluded.version, ''), version),
            publisher = COALESCE(NULLIF(excluded.publisher, ''), publisher),
            updated_at = CURRENT_TIMESTAMP
        """,
        (exe_path, target_path, icon_path, file_hash, version, publisher),
    )
    if cursor.lastrowid:
        return int(cursor.lastrowid)
    row = conn.execute(
        "SELECT id FROM binaries WHERE exe_path = ?",
        (exe_path,),
    ).fetchone()
    return int(row[0]) if row else None


def _normalise_source(raw: object) -> str:
    value = str(raw or "exe").lower()
    if value in {"uwp", "store"}:
        return "uwp"
    if value in {"shortcut", "lnk"}:
        return "shortcut"
    return "exe"


def _normalize_name(text: str) -> str:
    normalised = unicodedata.normalize("NFKD", text.lower())
    cleaned = "".join(ch for ch in normalised if unicodedata.category(ch) != "Mn")
    return " ".join(cleaned.split())


def _clean_str(value: object) -> Optional[str]:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


__all__ = [
    "DB_PATH",
    "ensure_schema",
    "load_apps",
    "ingest_scan",
    "scan_and_update_db",
]

